###
POST http://localhost:3001/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "secret_admin"
}

###
GET http://localhost:3001/login/role
Content-Type: application/json
Authorization: Bearer: <token>