###
GET http://localhost:3001/user
Content-Type: application/json

###
POST http://localhost:3001/user
Content-Type: application/json

{
  "username": "Jonas Pe de Pano",
  "email": "jonas@email.com",
  "password": "123456",
  "role": "user"
}

###
PUT http://localhost:3001/user/5
Content-Type: application/json

{
  "username": "José Dimas Santos",
  "email": "jose_dimas@sada.com",
  "role": "admin"
}

###
DELETE http://localhost:3001/user/5
