@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBlbWFpbC5jb20iLCJpYXQiOjE3NTIzNTIyOTUsImV4cCI6MTc1MjM1NTg5NX0.4EOvDhjGdlsDhtXdgCehbn3parCunORcAvv1uvq-nPQ
@BASE_URL = http://localhost:3001

### Create User
POST {{BASE_URL}}/user
Content-Type: application/json

{
  "username": "Jonas Pe de Pano",
  "email": "jonas@email.com",
  "password": "123456",
  "role": "user",
  "image": "https://rickandmortyapi.com/api/character/avatar/2.jpeg"
}

###
### Get All Users
GET {{BASE_URL}}/user
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
### Get User by ID
GET {{BASE_URL}}/user/3
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
### Update User
PUT {{BASE_URL}}/user/3
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "username": "José Dimas Santos",
  "email": "jose_dimas@sada.com",
  "role": "admin",
  "image": "https://rickandmortyapi.com/api/character/avatar/2.jpeg"
}

###
### Delete User
DELETE {{BASE_URL}}/user/3
Authorization: Bearer {{TOKEN}}

