services:
  node:
    build: .
    container_name: backend
    command: run dev
    working_dir: /api
    volumes:
      - ./src:/api/src
      - ./tests:/api/tests
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
    env_file:
      - .env.docker

  db:
    container_name: db
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: