[phases.build]
cmd = "npm run railway:build"

[phases.start]
cmd = "npm run railway:start"

[variables]
NPM_CONFIG_PRODUCTION = "false"
PGHOST = "{{.PGHOST}}"
PGPORT = "{{.PGPORT}}"
PGUSER = "{{.PGUSER}}"
PGPASSWORD = "{{.PGPASSWORD}}"
PGDATABASE = "{{.PGDATABASE}}"